### PR TITLE
add email in response closes #95

### LINKED ISSUE #95: It's now possible to get user's email address from Twitter, can we do this w/omniauth-twitter?
Buried at the bottom of this [Twitter Developer's forum post](https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558) a Twitter employee finally reveals that you can request access to get the user's email address from this [Twitter API Policy Support](https://support.twitter.com/forms/platform) form.

It is suggested to click the "I need access to special authentication privileges (e.g. xAuth)" radio button, and explain you want access to the user's email address. A common theme seems to be that Twitter support person misunderstands/denies/redirects you somewhere else (it happened to me too). But if you ask again, they will grant you access:

> We've enabled requesting email permissions for your app. Please note that this permission is only enabled on new sign-ins to your app. In order to begin, please log into apps.twitter.com and

* Add a terms of service and privacy policy to your app info
* Change your token's scope to request email

I also found a checkbox to select in my Twitter app's settings to enable the email permission.

I'm just stuck on how I might do this properly w/omniauth-twitter. I also use devise and it's omniauthable module. I see an array of permissions being used [here](https://github.com/arunagw/omniauth-twitter/blob/master/lib/omniauth/strategies/twitter.rb#L42), just not sure what to include and what else to do.

 I apologize for dumping all of this here, but I haven't seen anyone discussing how to solve this now that it's possible.

I am happy to try and submit a PR, any pointers would be appreciated I'm just digging into the code now.

### PR DESCRIPTION
**Pull request by raysrashmi**
To get email address in response
- Added ```include_email``` parameter in ```verify_credentials``` request
- Added email keys in raw_info hash

### CODE REVIEW

**Comment by arunagw** [comment]
LGTM

**Comment by MaicolBen** [comment]
@raysrashmi this get the account email? Because as far as I know twitter does not allow that (https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558)

**Comment by jeetdas** [comment]
Could you provide an example on how to use this? I am really confused.

**Comment by bobber205** [comment]
yeah I need an example too. I have emails included in my permissions but the gem doesn't return it

**Pull request merged**
