### PR TITLE
Allow use json 2.x versions

### PR DESCRIPTION
**Pull request by Fudoshiki**

### CODE REVIEW

**Comment by connorshea** [comment]
Need to lock rack to 1.x for versions prior to Ruby 2.2, should also probably test the gem on Ruby 2.3.

**Comment by connorshea** [comment]
Oh, and the reason for allowing json 2.x is that json 1.x doesn't currently support Ruby 2.4.

**Comment by SamSaffron** [comment]
yes ... please drop it altogether ❤️

**Comment by arunagw** [comment]
I have prepared #113. Please have a look.

**Comment by arunagw** [comment]
I think we are good with #114 now.

**Pull request closed without merging**
