### PR TITLE
Allow passing a callback_url param

### PR DESCRIPTION
**Pull request by bzf**
When building an application we need to do two types of Twitter
authentication - one for signing in to our application (and creating a
`User`) and another for associating Twitter accounts to their `User`
account.

By passing a custom `callback_url` param we can have one controller
method for signing in and another one for the associating part and just
have the application set the callback when starting the authentication
process.

### CODE REVIEW

**Comment by bzf** [comment]
There seems to be some install errors on CI. It's also dipping under the 94% coverage limit due to not adding a test.

Also, when the request comes back from Twitter the `request.env["omniauth.auth"]` value is `nil` - do you know anything about what might've caused that?

**Comment by raysrashmi** [comment]
Thanks for the PR.
  Reason behind getting `request.env["omniauth.auth"]` as nil is because it is not going in to `callback_phase` method where we assign `auth_hash` to `env['omniauth.auth']`  [see here](https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb#L361). So basically we need to set   `options[:callback]` same as `callback_url` or either override `callaback_path` [method](https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb#L383)

**Comment by bzf** [comment]
@raysrashmi Alright, I've tried overriding the `callback_path` method and I did not get it to work. I've looked through the links you sent but could not understand how everything fits together. Would you have time to pair on this sometime, or help me by pointing me into the right direction? 😃

**Comment by raysrashmi** [comment]
@bzf I think its fine to use session and I don't think there is any other way to get callback_url.  👍  for tests.

**Comment by raysrashmi** [comment]
@bzf Any update on this?

**Comment by bzf** [comment]
@raysrashmi Sorry that I haven't responded! I'll try to write up a test today!

**Comment by bzf** [comment]
Added a spec in the latest commit

**Comment by raysrashmi** [comment]
@bzf Thank you for the specs. I found on issue in `callback_url` when there is no params['callback_url'] it just redirect for Pin based login so we need to call parent't class `callback_url`. I have pushed a commit  https://github.com/arunagw/omniauth-twitter/commit/91485a4ea1760c72b0314ca8fb20c29aeb6b7929 have a look and if you find good cherry-pick in your branch

**Comment by bzf** [comment]
@raysrashmi Cherry picked! 👍

**Comment by raysrashmi** [comment]
@bzf Released a new version 1.4.0 😊 . Thank you so much for the PR ❤️

**Comment by bzf** [comment]
@raysrashmi Thanks for merging it! 😄 ❤️

**Comment by chriso0710** [comment]
also see #103

**Pull request merged**
